### ISSUE TITLE
Intro to Storybook　実践memo

### ISSUE THREAD

**Issue by YukoKano** [YukoKano/storybook-tutorial#1]

**Comment by YukoKano** [comment]
サンプル通りにやったのにyarn test --watchAllでtestないよって言われた

**Comment by YukoKano** [comment]
```
yarn add jest
```
してpackage.jsonを追加して直った
```
"scripts": {
    "test": "jest --watchAll"
  }
```

**Comment by YukoKano** [comment]
>このコミュニティの翻訳は、最新の Storybook バージョンに対応していません。英語ガイドの最新の変更を適用して、この日本語ガイドの更新にご協力ください。 [Pull requests を大歓迎します。](https://github.com/chromaui/learnstorybook.com/blob/master/content/intro-to-storybook/react/ja/simple-component.md)

バージョンが古かったからおかしかったのかもしれん　今8だもんね

**Comment by YukoKano** [comment]
```
ou@kurogoma taskbox % yarn storybook
yarn run v1.22.19
warning ../../../../package.json: No license field
$ storybook dev -p 6006
@storybook/cli v8.1.4

SB_CORE-COMMON_0002 (InvalidFrameworkNameError): Invalid value of '@storybook/react' in the 'framework' field of Storybook config.

Please run 'npx storybook automigrate' to automatically fix your config.

More info: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#new-framework-api

    at validateFrameworkName (./node_modules/@storybook/core-common/dist/index.js:50:2172)
    at buildDevStandalone (./node_modules/@storybook/core-server/dist/index.js:65:1673)
    at async withTelemetry (./node_modules/@storybook/core-server/dist/index.js:28:3599)
    at async dev (./node_modules/@storybook/cli/dist/generate.js:705:563)
    at async Command.<anonymous> (./node_modules/@storybook/cli/dist/generate.js:707:250)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

WARN Could not resolve addon "@storybook/preset-create-react-app", skipping. Is it installed?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

>npx storybook automigrate

したらよしなに調整してくれたっぽい、？

**Comment by YukoKano** [comment]
これダメだ、作り直します。

**Comment by YukoKano** [comment]
作り直した、次は「Build out the states」から
https://storybook.js.org/tutorials/intro-to-storybook/react/en/simple-component/

**Comment by YukoKano** [comment]
きちんと型定義しないとこういうエラーが出るっぽい

<img width="634" alt="image" src="https://github.com/YukoKano/storybook-tutorial/assets/38373129/44b354ef-601f-4371-a4c7-c35c5ed7b6c2">

**Comment by YukoKano** [comment]
アクセシビリティの問題をキャッチ、から

**Comment by YukoKano** [comment]
Addon でこういうパネルも検証することができるのか

![image](https://github.com/YukoKano/storybook-tutorial/assets/38373129/1b4d8d66-e543-4da1-b845-bd4ac11d2d92)

**Comment by YukoKano** [comment]
次はここから
https://storybook.js.org/tutorials/intro-to-storybook/react/en/composite-component/

**Comment by YukoKano** [comment]
![image](https://github.com/YukoKano/storybook-tutorial/assets/38373129/e8eb366b-b0be-4bd3-8fae-37c444398b51)

**Comment by YukoKano** [comment]
Data requirements and props から

**Comment by YukoKano** [comment]
PropTypes、非推奨になってるやんけ

https://ja.react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops

早めにTypeScriptやっといたほうがいいんだろうか

**Comment by YukoKano** [comment]
TODO：const { hoge }　import { hoge } 、とconst hoge import hoge、で何が違うのか記事書く

**Comment by kano-yuko** [comment]
山田さん）argsでどういう挙動になるのかが分かれば良さそう

**Comment by YukoKano** [comment]
ページをStoryして、エラーが出ると書いてあったけど特段エラーは出てないんだよな、
![image](https://github.com/user-attachments/assets/75b71e9e-47e1-4976-9aa1-3f4ac47ff394)


Mocking API Servicesから続きやる

↑エラーページがちゃんとエラーページを吐かないのがエラーだったっぽい

**Comment by YukoKano** [comment]
```
yarn test-storybook --watch
```

をするためにはStorybook立ち上げておかないといけないっぽい

>Storybook's test runner requires either a locally running Storybook instance or a published Storybook to run all the existing tests.

---

動いたが、テスト環境ないよって言われて、これを↓たたいた
```
yarn playwright install  
```
自動テストのためのツールっぽい

>yarn playwright installコマンドは、[Playwright](https://playwright.dev/)のブラウザバイナリをインストールするためのコマンドです。Playwrightは、Node.js用のエンドツーエンドテストツールで、Chromium、Firefox、WebKitなどの異なるブラウザで自動テストを実行することができます。

>yarn playwright installコマンドは、Playwrightが初めてインストールされたときに一度だけ実行すれば十分です。その後のテスト実行時には、インストールされたブラウザバイナリを利用するだけで済みます。
例えば、@storybook/test-runnerはPlaywrightを使用してStorybookのコンポーネントをテストするため、yarn playwright installが必要になることがあります。


---

通った↓

<img width="688" alt="image" src="https://github.com/user-attachments/assets/8436db72-9f77-44db-a5bd-00ec7489997a">

**Comment by YukoKano** [comment]
```
import {
  fireEvent,
  waitFor,
  within,
  waitForElementToBeRemoved,
} from "@storybook/test";
```

この辺からの記述がわからん

**Comment by YukoKano** [comment]
TODO：GitHub Actionsを使えるように、アクセストークンを設定する

**Comment by YukoKano** [comment]
変数を設定した

![image](https://github.com/user-attachments/assets/a50d3d33-00b8-4a5c-9757-5fd64f44a496)

**Comment by YukoKano** [comment]
ファイルの依存関係がおかしくなっていてずっとエラーが出ているので修正している

**Comment by YukoKano** [comment]
通った〜〜〜〜〜〜〜〜〜〜！ChatGPTありがとう！！！！！

![image](https://github.com/user-attachments/assets/da862138-cb0a-4494-b96a-713dfe1374de)

**Comment by YukoKano** [comment]
学び：
- Actionsのワークフローを使う場合、サイトから環境変数を設定する（GITHUB_から始まるのはNGでした）
- コケるエラーをよくみて、一個ずつ潰す、何か間違っていれば依存関係の問題っぽい
  - 一旦ChatGPTに投げると原因まとめてくれるからめっちゃわかりやすい

**Comment by YukoKano** [comment]
あんがとね

![image](https://github.com/user-attachments/assets/b128b11b-4835-45c4-94df-7610ebf804f3)

**Comment by YukoKano** [comment]
Visual Testsからやる

**Comment by YukoKano** [comment]
終わった〜！

**Comment by YukoKano** [comment]
1日30分、約11日で完了している　＝330分　＝6時間半
